### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by spicyShrimp** [rocwangv/react-native-redux-navigation#4]
开始报找不到CardStackStyleInterpolator错误,原因是react-navigation修改了文件路径,
修正后还是报错,
此时报的是undefined is not a function (near '...addListener...')

**Comment by rocwong-cn** [comment]
好的，我晚上看下，应该是`react-navigation`版本升级导致。

**Comment by spicyShrimp** [comment]
demo中能否再添加TabNavigator的使用?

**Comment by rocwong-cn** [comment]
可以了，拉一下新代码
```
git pull

npm i
react-native run-ios
```

ps: *react-navigation*官方更改了redux的集成方式，参见：[Redux integration](https://reactnavigation.org/docs/redux-integration.html)
